# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCdw60VkJXYlPmlBkVWql1jG8egD65hk
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Insurance Purchase Prediction",
    page_icon="📊",
    layout="wide"
)

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.title("Developer Info")
st.sidebar.markdown(
    "[🔗 GitHub Profile](https://github.com/Priea05)"
)

# Visitor Counter
if "visitor_count" not in st.session_state:
    st.session_state.visitor_count = 0

st.session_state.visitor_count += 1

st.sidebar.metric(
    "Page Visits (Current Session)",
    st.session_state.visitor_count
)

# Prediction Counter
if "prediction_count" not in st.session_state:
    st.session_state.prediction_count = 0

st.sidebar.metric(
    "Predictions Made",
    st.session_state.prediction_count
)

# -----------------------------
# Title
# -----------------------------
st.title("📊 Insurance Purchase Prediction")
st.write("### Logistic Regression Model")

# -----------------------------
# Load Dataset
# -----------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------
# Scatter Plot
# -----------------------------
st.subheader("Age vs Bought Insurance")

fig, ax = plt.subplots()

ax.scatter(
    df["age"],
    df["bought_insurance"],
    marker="+",
    color="red"
)

ax.set_xlabel("Age")
ax.set_ylabel("Bought Insurance")

st.pyplot(fig)

# -----------------------------
# Train/Test Split
# -----------------------------
X = df[["age"]]
y = df["bought_insurance"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.8,
    random_state=42
)

# -----------------------------
# Model Training
# -----------------------------
model = LogisticRegression()
model.fit(X_train, y_train)

# -----------------------------
# Model Accuracy
# -----------------------------
accuracy = model.score(X_test, y_test)

st.subheader("Model Accuracy")
st.success(f"{accuracy*100:.2f}%")

# -----------------------------
# Model Parameters
# -----------------------------
st.subheader("Model Parameters")
st.write("Coefficient:", model.coef_[0][0])
st.write("Intercept:", model.intercept_[0])

# -----------------------------
# Prediction
# -----------------------------
st.subheader("Predict Insurance Purchase")

age = st.number_input(
    "Enter Age",
    min_value=1,
    max_value=100,
    value=30
)

if st.button("Predict"):

    st.session_state.prediction_count += 1

    # Create DataFrame for prediction
    input_data = pd.DataFrame({"age": [age]})

    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    st.write(f"Probability of Buying Insurance: **{probability:.2%}**")

    st.progress(int(probability * 100))

    if prediction == 1:
        st.success("✅ The person is likely to buy insurance.")
    else:
        st.error("❌ The person is not likely to buy insurance.")

    st.sidebar.metric(
        "Predictions Made",
        st.session_state.prediction_count
    )

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.markdown(
    "Developed with ❤️ using Streamlit | "
    "[GitHub](https://github.com/Priea05)"
)